# Generated by Django 5.0.3 on 2024-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='المنتجات',
            name='الصورة',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image'),
        ),
    ]
