# Generated by Django 5.0.3 on 2024-09-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_product_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Request'), ('return', 'Return Request')], default='new', max_length=20, verbose_name='Request Type'),
        ),
    ]
