# Generated by Django 5.0.3 on 2024-05-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_المنتجات_الصورة'),
    ]

    operations = [
        migrations.AlterField(
            model_name='المخزون',
            name='المنتجات',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.المنتجات'),
        ),
    ]
