# Generated by Django 5.0.3 on 2024-09-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_المخزون_المنتجات'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='المخزون',
            options={'verbose_name': 'مخزون', 'verbose_name_plural': 'المخزون'},
        ),
        migrations.AlterModelOptions(
            name='المنتجات',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterField(
            model_name='المخزون',
            name='الكمية',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='المخزون',
            name='المنتجات',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.المنتجات'),
        ),
    ]
