# Generated by Django 5.0.3 on 2024-09-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.facility', verbose_name='Facility'),
        ),
    ]
