# Generated by Django 5.0.3 on 2024-10-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_facility'),
        ('devices', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facility',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.facility', verbose_name='Facility'),
        ),
    ]
